final List specializations = [
  'alergologia',
  'anestezjologia i intensywna terapia',
  'angiologia',
  'audiologia i foniatria',
  'balneologia i medycyna fizykalna',
  'chirurgia dziecięca',
  'chirurgia klatki piersiowej',
  'chirurgia naczyniowa',
  'chirurgia ogólna',
  'chirurgia onkologiczna',
  'chirurgia plastyczna',
  'chirurgia szczękowo-twarzowa',
  'choroby płuc',
  'choroby płuc dzieci',
  'choroby wewnętrzne',
  'choroby zakaźne',
  'dermatologia i wenerologia',
  'diabetologia',
  'diagnostyka laboratoryjna',
  'endokrynologia',
  'endokrynologia ginekologiczna i rozrodczość',
  'endokrynologia i diabetologia dziecięca',
  'epidemiologia',
  'farmakologia kliniczna',
  'gastroenterologia',
  'gestroenterologia dziecięca',
  'genetyka kliniczna',
  'geriatria',
  'ginekologia onkologiczna',
  'hematologia',
  'hipertensjologia',
  'immunologia kliniczna',
  'intensywna terapia',
  'kardiochirurgia',
  'kardiologia',
  'kardiologia dziecięca',
  'medycyna lotnicza',
  'medycyna morska i tropikalna',
  'medycyna nuklearna',
  'medycyna paliatywna',
  'medycyna pracy',
  'medycyna ratunkowa',
  'medycyna rodzinna',
  'medycyna sądowa',
  'medycyna sportowa',
  'mikrobilogia lekarska',
  'nefrologia',
  'nefrologia dziecięca',
  'neonatologia',
  'neurochirurgia',
  'neurologia',
  'neurologia dziecięca',
  'neuropatologia',
  'okulistyka',
  'onkologia i hematologia dziecięca',
  'onkologia kliniczna',
  'ortopedia i traumatologia narządu ruchu',
  'otorynolaryngologia',
  'otorynolaryngologia dziecięca',
  'patomorfologia',
  'pediatria',
  'pediatria metaboliczna',
  'perinatologia',
  'położnictwo i ginekologia',
  'psychiatria',
  'psychiatria dzieci i młodzieży',
  'radiologia i diagnostyka obrazowa',
  'radioterapia onkologiczna',
  'rehabilitacja medyczna',
  'reumatologia',
  'seksuologia',
  'toksykologia kliniczna',
  'transfuzjologia kliniczna',
  'urologia',
  'urologia dziecięca',
  'zdrowie publiczne'
];
